version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.12
    steps:
      - checkout
      # Cache deps
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run: mvn -B -V dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      # Build and install artifacts
      - run: mvn -B -V clean install -DskipTests -Dgpg.skip=true -Dmaven.javadoc.skip=true
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  test-release:
    docker:
      - image: cimg/openjdk:11.0.12
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run: mvn -B -V -DdryRun=true release:prepare -Darguments="-Dgpg.skip=true -DskipTests"
      - run: mvn -B -V -DdryRun=true release:perform -Darguments="-Dgpg.skip=true -DskipTests"

  test-jdk:
    parameters:
      jdk:
        type: string
    docker:
      - image: << parameters.jdk >>
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      # Install artifacts without re-compiling
      - run: mvn -B -V install -Dgpg.skip=true -Dmaven.javadoc.skip=true -Dmaven.main.skip=true -Dmaven.test.skip=true -Dfmt.skip=true
      # Excercise the JDK 11 built annotation processor using the selected JDK:
      # 1. Run all tests
      - run: mvn -B -V surefire:test
      # 2. Compile examples
      - run: mvn -B -V clean test -pl example -Dfmt.skip=true
      # 3. Compile and run tests
      - run: mvn -B -V clean test -pl test -Dfmt.skip=true

  jackson-it:
    parallelism: 4
    docker:
      - image: cimg/openjdk:11.0.12
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Install artifacts
          command: mvn -B -V install -DskipTests -Dgpg.skip=true -Dmaven.javadoc.skip=true
      - run:
          name: Test Jackson Versions
          command: ./jackson-it.sh

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test-release
      - jackson-it:
          requires: [build]
      - test-jdk:
          requires: [build]
          name: 8 - AdoptOpenJDK
          jdk: "cimg/openjdk:8.0.302"
      - test-jdk:
          requires: [build]
          name: 11 - AdoptOpenJDK
          jdk: "cimg/openjdk:11.0.12"
      - test-jdk:
          requires: [build]
          name: 15 - AdoptOpenJDK
          jdk: "cimg/openjdk:15.0.2"
      - test-jdk:
          requires: [build]
          name: 11 - Amazon Corretto
          jdk: "amazoncorretto:11"
      - test-jdk:
          requires: [build]
          name: 17 - AdoptOpenJDK
          jdk: "cimg/openjdk:17.0.0"
      - test-jdk:
          requires: [build]
          name: 11 - Azul Zulu
          jdk: "azul/zulu-openjdk:11"
      - test-jdk:
          requires: [build]
          name: 17 - Amazon Corretto
          jdk: "amazoncorretto:17"
      - test-jdk:
          requires: [build]
          name: 11 - GraalVM CE
          jdk: "ghcr.io/graalvm/graalvm-ce:java11-21"
      - test-jdk:
          requires: [build]
          name: 17 - Azul Zulu
          jdk: "ghcr.io/graalvm/graalvm-ce:java17-21"
